### ISSUE TITLE
Dashboard for Term

### ISSUE THREAD

**Issue by yeuem1vannam** [yeuem1vannam/Minerva#17]
Definition of done:
- [x] CRUD Term

Reference:
- https://github.com/thoughtbot/administrate gem
- [user_dashboard.rb](https://github.com/yeuem1vannam/Minerva/blob/master/app/dashboards/user_dashboard.rb)

**Comment by dutavi** [comment]
test 
với admin có thể vào được đường dẫn x/y/z mà không bị lỗi 
với user k thể vào được đường dẫn x/y/z.
p/s:
-Cháu vẫn chưa hiểu cái test này lắm chú ạ . 
( term và phrase đều chung 1 test này hay là Term 1 test và Pharase 1 test.).
vì cháu thấy chú tạo 2 task : 
task 1: Term Dashboard. 
task 2 : Phrase Dashboard. 
và khi chú bảo viết test chỉ  bảo test  như trên nên bây h cháu vẫn chưa hình dung ra.

**Comment by yeuem1vannam** [comment]
1. Một issue chỉ target đến 1 vấn đề, issue này cho Term nên chỉ làm cho Term thôi.
  -> Test ở đây là dành cho Term Dashboard
2. Test chỉ target vào 1 subject cụ thể, nên sẽ không có chuyện test chung. Nếu như /admin có 1000 url thứ cấp thì về mặt lý thuyết mình phải test đủ 1000 cái đó.
3. Test có thể chia ra làm nhiều cấp từ dễ đến khó, mức độ ý nghĩa của test. Tuỳ thuộc vào thời gian và khả năng mà chúng ta sẽ viết những test nào cho phù hợp.
  - Test 1: Admin access được /admin/terms còn user bình thường thì không -> test dễ nhưng ý nghĩa cực lớn
  - Test 2: Admin có thể tạo Term -> test trung bình, ý nghĩa trung bình
  - Test 3: Admin có thể xoá Term -> test trung bình, ý nghĩa khá thấp (vì trong thực tế, chuyện xoá data rất ít khi dùng)

**Comment by dutavi** [comment]
Chú có thể add thêm file test của cái Dashboard for user vào task, cho cháu thêm tài liệu được k ?

**Comment by yeuem1vannam** [comment]
@dutavi https://github.com/yeuem1vannam/Minerva/tree/master/spec/features/admin/users
Test này đây thôi ?

**Comment by yeuem1vannam** [comment]
Dashboard cần các phần như sau:
- Route: `config/routes.rb`
- Controller: `app/controllers/admin/terms_controller.rb`
- Dashboard: `app/dashboards/term_dashboard.rb`
- Policy: `app/policies/term_policy.rb`

**Comment by dutavi** [comment]
#\\
![Screenshot from 2019-07-09 16-27-03](https://user-images.githubusercontent.com/43242076/60876660-8a2bc900-a266-11e9-92a3-372e932d2549.png)
-Chạy test dưới xanh mà đẩy lên lại lại báo hỏng. :(
